#!/bin/bash
pandoc -f html -t epub3 -o juliadocs.epub \
index.html \
manual/getting-started.html \
manual/installation.html \
manual/variables.html \
manual/integers-and-floating-point-numbers.html \
manual/mathematical-operations.html \
manual/complex-and-rational-numbers.html \
manual/strings.html \
manual/functions.html \
manual/control-flow.html \
manual/variables-and-scoping.html \
manual/types.html \
manual/methods.html \
manual/constructors.html \
manual/conversion-and-promotion.html \
manual/interfaces.html \
manual/modules.html \
manual/documentation.html \
manual/metaprogramming.html \
manual/arrays.html \
manual/missing.html \
manual/networking-and-streams.html \
manual/parallel-computing.html \
manual/asynchronous-programming.html \
manual/multi-threading.html \
manual/distributed-computing.html \
manual/running-external-programs.html \
manual/calling-c-and-fortran-code.html \
manual/handling-operating-system-variation.html \
manual/environment-variables.html \
manual/embedding.html \
manual/code-loading.html \
manual/profile.html \
manual/stacktraces.html \
manual/memory-management.html \
manual/performance-tips.html \
manual/workflow-tips.html \
manual/style-guide.html \
manual/faq.html \
manual/noteworthy-differences.html \
manual/unicode-input.html \
manual/command-line-interface.html \
manual/worldage.html \
base/base.html \
base/collections.html \
base/math.html \
base/numbers.html \
base/strings.html \
base/arrays.html \
base/parallel.html \
base/multi-threading.html \
base/scopedvalues.html \
base/constants.html \
base/file.html \
base/io-network.html \
base/punctuation.html \
base/sort.html \
base/iterators.html \
base/reflection.html \
base/c.html \
base/libc.html \
base/stacktraces.html \
stdlib/ArgTools.html \
stdlib/Artifacts.html \
stdlib/Base64.html \
stdlib/CRC32c.html \
stdlib/Dates.html \
stdlib/DelimitedFiles.html \
stdlib/Distributed.html \
stdlib/Downloads.html \
stdlib/Libdl.html \
stdlib/FileWatching.html \
stdlib/Future.html \
stdlib/InteractiveUtils.html \
stdlib/JuliaSyntaxHighlighting.html \
stdlib/LazyArtifacts.html \
stdlib/LibCURL.html \
stdlib/LibGit2.html \
stdlib/LinearAlgebra.html \
stdlib/Logging.html \
stdlib/Markdown.html \
stdlib/Mmap.html \
stdlib/NetworkOptions.html \
stdlib/Pkg.html \
stdlib/Printf.html \
stdlib/Profile.html \
stdlib/Random.html \
stdlib/REPL.html \
stdlib/Serialization.html \
stdlib/SHA.html \
stdlib/SharedArrays.html \
stdlib/Sockets.html \
stdlib/SparseArrays.html \
stdlib/Statistics.html \
stdlib/StyledStrings.html \
stdlib/Tar.html \
stdlib/TOML.html \
stdlib/Unicode.html \
stdlib/Test.html \
stdlib/UUIDs.html \
devdocs/init.html \
devdocs/ast.html \
devdocs/types.html \
devdocs/object.html \
devdocs/eval.html \
devdocs/callconv.html \
devdocs/compiler.html \
devdocs/functions.html \
devdocs/cartesian.html \
devdocs/meta.html \
devdocs/subarrays.html \
devdocs/isbitsunionarrays.html \
devdocs/sysimg.html \
devdocs/pkgimg.html \
devdocs/llvm-passes.html \
devdocs/llvm.html \
devdocs/stdio.html \
devdocs/boundscheck.html \
devdocs/locks.html \
devdocs/offset-arrays.html \
devdocs/require.html \
devdocs/inference.html \
devdocs/ssair.html \
devdocs/EscapeAnalysis.html \
devdocs/aot.html \
devdocs/gc-sa.html \
devdocs/gc.html \
devdocs/gc-mmtk.html \
devdocs/jit.html \
devdocs/builtins.html \
devdocs/precompile_hang.html \
devdocs/backtraces.html \
devdocs/debuggingtips.html \
devdocs/valgrind.html \
devdocs/external_profilers.html \
devdocs/sanitizers.html \
devdocs/probes.html \
devdocs/build/build.html \
devdocs/build/linux.html \
devdocs/build/macos.html \
devdocs/build/windows.html \
devdocs/build/freebsd.html \
devdocs/build/arm.html \
devdocs/build/riscv.html \
devdocs/build/distributing.html \
devdocs/contributing/code-changes.html \
devdocs/contributing/tests.html \
devdocs/contributing/documentation.html \
devdocs/contributing/jldoctests.html \
devdocs/contributing/patch-releases.html \
devdocs/contributing/formatting.html \
devdocs/contributing/git-workflow.html \
devdocs/contributing/aiagents.html \
