cd \\wsl.localhost\AlmaLinux-10\home\franemar\git\default\julia\doc

pandoc -f html -t epub3 ^
_build\html\README.html ^
_build\html\manual\getting-started.html ^
_build\html\manual\installation.html ^
_build\html\manual\variables.html ^
_build\html\manual\integers-and-floating-point-numbers.html ^
_build\html\manual\mathematical-operations.html ^
_build\html\manual\complex-and-rational-numbers.html ^
_build\html\manual\strings.html ^
_build\html\manual\functions.html ^
_build\html\manual\control-flow.html ^
_build\html\manual\variables-and-scoping.html ^
_build\html\manual\types.html ^
_build\html\manual\methods.html ^
_build\html\manual\constructors.html ^
_build\html\manual\conversion-and-promotion.html ^
_build\html\manual\interfaces.html ^
_build\html\manual\modules.html ^
_build\html\manual\documentation.html ^
_build\html\manual\metaprogramming.html ^
_build\html\manual\arrays.html ^
_build\html\manual\missing.html ^
_build\html\manual\networking-and-streams.html ^
_build\html\manual\parallel-computing.html ^
_build\html\manual\asynchronous-programming.html ^
_build\html\manual\multi-threading.html ^
_build\html\manual\distributed-computing.html ^
_build\html\manual\running-external-programs.html ^
_build\html\manual\calling-c-and-fortran-code.html ^
_build\html\manual\handling-operating-system-variation.html ^
_build\html\manual\environment-variables.html ^
_build\html\manual\embedding.html ^
_build\html\manual\code-loading.html ^
_build\html\manual\profile.html ^
_build\html\manual\stacktraces.html ^
_build\html\manual\memory-management.html ^
_build\html\manual\performance-tips.html ^
_build\html\manual\workflow-tips.html ^
_build\html\manual\style-guide.html ^
_build\html\manual\faq.html ^
_build\html\manual\noteworthy-differences.html ^
_build\html\manual\unicode-input.html ^
_build\html\manual\command-line-interface.html ^
_build\html\manual\worldage.html ^
_build\html\base\base.html ^
_build\html\base\collections.html ^
_build\html\base\math.html ^
_build\html\base\numbers.html ^
_build\html\base\strings.html ^
_build\html\base\arrays.html ^
_build\html\base\parallel.html ^
_build\html\base\multi-threading.html ^
_build\html\base\scopedvalues.html ^
_build\html\base\constants.html ^
_build\html\base\file.html ^
_build\html\base\io-network.html ^
_build\html\base\punctuation.html ^
_build\html\base\sort.html ^
_build\html\base\iterators.html ^
_build\html\base\reflection.html ^
_build\html\base\c.html ^
_build\html\base\libc.html ^
_build\html\base\stacktraces.html ^
_build\html\base\sihtml-types.html ^
_build\html\stdlib\ArgTools.html ^
_build\html\stdlib\Artifacts.html ^
_build\html\stdlib\Base64.html ^
_build\html\stdlib\CRC32c.html ^
_build\html\stdlib\Dates.html ^
_build\html\stdlib\DelimitedFiles.html ^
_build\html\stdlib\Distributed.html ^
_build\html\stdlib\Downloads.html ^
_build\html\stdlib\Libdl.html ^
_build\html\stdlib\FileWatching.html ^
_build\html\stdlib\Future.html ^
_build\html\stdlib\InteractiveUtils.html ^
_build\html\stdlib\JuliaSyntaxHighlighting.html ^
_build\html\stdlib\LazyArtifacts.html ^
_build\html\stdlib\LibCURL.html ^
_build\html\stdlib\LibGit2.html ^
_build\html\stdlib\LinearAlgebra.html ^
_build\html\stdlib\Logging.html ^
_build\html\stdlib\Markdown.html ^
_build\html\stdlib\Mmap.html ^
_build\html\stdlib\NetworkOptions.html ^
_build\html\stdlib\Pkg.html ^
_build\html\stdlib\Printf.html ^
_build\html\stdlib\Profile.html ^
_build\html\stdlib\Random.html ^
_build\html\stdlib\REPL.html ^
_build\html\stdlib\Serialization.html ^
_build\html\stdlib\SHA.html ^
_build\html\stdlib\SharedArrays.html ^
_build\html\stdlib\Sockets.html ^
_build\html\stdlib\SparseArrays.html ^
_build\html\stdlib\Statistics.html ^
_build\html\stdlib\StyledStrings.html ^
_build\html\stdlib\Tar.html ^
_build\html\stdlib\TOML.html ^
_build\html\stdlib\Unicode.html ^
_build\html\stdlib\Test.html ^
_build\html\stdlib\UUIDs.html ^
_build\html\devdocs\init.html ^
_build\html\devdocs\ast.html ^
_build\html\devdocs\types.html ^
_build\html\devdocs\object.html ^
_build\html\devdocs\eval.html ^
_build\html\devdocs\callconv.html ^
_build\html\devdocs\compiler.html ^
_build\html\devdocs\functions.html ^
_build\html\devdocs\cartesian.html ^
_build\html\devdocs\meta.html ^
_build\html\devdocs\subarrays.html ^
_build\html\devdocs\isbitsunionarrays.html ^
_build\html\devdocs\sysimg.html ^
_build\html\devdocs\pkgimg.html ^
_build\html\devdocs\llvm-passes.html ^
_build\html\devdocs\llvm.html ^
_build\html\devdocs\stdio.html ^
_build\html\devdocs\boundscheck.html ^
_build\html\devdocs\locks.html ^
_build\html\devdocs\offset-arrays.html ^
_build\html\devdocs\require.html ^
_build\html\devdocs\inference.html ^
_build\html\devdocs\ssair.html ^
_build\html\devdocs\EscapeAnalysis.html ^
_build\html\devdocs\aot.html ^
_build\html\devdocs\gc-sa.html ^
_build\html\devdocs\gc.html ^
_build\html\devdocs\gc-mmtk.html ^
_build\html\devdocs\jit.html ^
_build\html\devdocs\builtins.html ^
_build\html\devdocs\precompile_hang.html ^
_build\html\devdocs\backtraces.html ^
_build\html\devdocs\debuggingtips.html ^
_build\html\devdocs\valgrind.html ^
_build\html\devdocs\external_profilers.html ^
_build\html\devdocs\sanitizers.html ^
_build\html\devdocs\probes.html ^
_build\html\devdocs\build\build.html ^
_build\html\devdocs\build\linux.html ^
_build\html\devdocs\build\macos.html ^
_build\html\devdocs\build\windows.html ^
_build\html\devdocs\build\freebsd.html ^
_build\html\devdocs\build\arm.html ^
_build\html\devdocs\build\riscv.html ^
_build\html\devdocs\build\distributing.html ^
_build\html\devdocs\contributing\code-changes.html ^
_build\html\devdocs\contributing\tests.html ^
_build\html\devdocs\contributing\documentation.html ^
_build\html\devdocs\contributing\jldoctests.html ^
_build\html\devdocs\contributing\patch-releases.html ^
_build\html\devdocs\contributing\formatting.html ^
_build\html\devdocs\contributing\git-workflow.html ^
_build\html\devdocs\contributing\aiagents.html ^
 -o juliadocs.epub
